### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by ywj55555** [xiaomingnio/pp_liteseg_pytorch#1]
请问训练的时候，是三个一样的损失吗？

**Comment by LumenForgeX** [comment]
是的，三个loss都是OhemCrossEntropyLoss

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 130000   # batch_size * 1024 * 512 // 16
    - type: OhemCrossEntropyLoss
      min_kept: 130000
    - type: OhemCrossEntropyLoss
      min_kept: 130000
  coef: [1, 1, 1]

这是pp_liteseg的loss设置
